### ISSUE TITLE
Fix deprecated set-output

### ISSUE THREAD

**Issue by jonmelia** [matt-FFFFFF/simple-semver#1]
`      run: echo "semver-output=$(${{ github.action_path}}/simplesemver.sh -${{ inputs.increment }} -v ${{ inputs.semver-input }} )" >> $GITHUB_OUTPUT`

as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by matt-FFFFFF** [comment]
Thanks for raising, updated in 967d66a. Wil test then release a new version!

**Comment by rajbos** [comment]
Hi @matt-FFFFFF, the version from `main` works just fine, can you please release that newer version to help folks using the latest without any warnings 🤗.

**Comment by matt-FFFFFF** [comment]
Hi - fixed in v0.1.1, apologies!

**Comment by rajbos** [comment]
Great! Thanks :-)
